apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jam-prizes-data
  namespace: jam-prizes-prod
  labels:
    app.kubernetes.io/name: jam-prizes
    app.kubernetes.io/part-of: jam-prizes
    environment: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
